# main.yml
---
- name: Create nipap group
  group:
    name: "{{ nipap_group }}"

- name: Create nipap user and home directory
  user:
    name: "{{ nipap_user }}"
    group: "{{ nipap_group }}"
    home: "{{ nipap_home }}"

- name: Clone NIPAP repository
  ansible.builtin.git:
    repo: https://github.com/SpriteLink/NIPAP.git
    dest: /usr/share/nipap
    version: v0.32.5

- name: Install required packages for building ip4r
  ansible.builtin.dnf:
    name:
      - git
      - make
      - gcc
    state: present

- name: Clone ip4r repository
  ansible.builtin.git:
    repo: https://github.com/RhodiumToad/ip4r.git
    dest: /tmp/ip4r

- name: Build ip4r extension
  ansible.builtin.command:
    cmd: make
    chdir: /tmp/ip4r
    creates: /tmp/ip4r/ip4r.so
  environment:
    PATH: "/usr/pgsql-17/bin:{{ ansible_env.PATH }}"

- name: Install ip4r extension
  ansible.builtin.command:
    cmd: make install
    chdir: /tmp/ip4r
    creates: /usr/pgsql-17/lib/ip4r.so
  environment:
    PATH: "/usr/pgsql-17/bin:{{ ansible_env.PATH }}"

- name: Ensure PostgreSQL extensions are installed
  become_user: postgres
  community.postgresql.postgresql_ext:
    name: "{{ item }}"
    login_user: postgres
    login_unix_socket: /var/run/postgresql
    db: "{{ nipap_database }}"
  loop:
    - ip4r
    - hstore
    - citext

- name: Install OpenLDAP development libraries
  ansible.builtin.dnf:
    name: openldap-devel
    state: present

- name: Create virtual environment for NIPAP
  ansible.builtin.command:
    cmd: python3 -m venv /usr/share/nipap/venv
  args:
    creates: /usr/share/nipap/venv/bin/activate

- name: Install the required Python packages from requirements.txt in the virtual environment
  ansible.builtin.pip:
    requirements: /usr/share/nipap/nipap/requirements.txt
    virtualenv: /usr/share/nipap/venv
  environment:
    PATH: "/usr/share/nipap/venv/bin:/usr/pgsql-17/bin:{{ ansible_env.PATH }}"

- name: Install nipapd daemon in the virtual environment
  ansible.builtin.command:
    cmd: /usr/share/nipap/venv/bin/python setup.py install
    chdir: /usr/share/nipap/nipap

- name: Reinstall docutils in the virtual environment
  ansible.builtin.pip:
    name: docutils==0.21.1
    state: forcereinstall
    virtualenv: /usr/share/nipap/venv

- name: Install NIPAP CLI client in virtual environment
  ansible.builtin.command:
    cmd: /usr/share/nipap/venv/bin/pip install .
    chdir: /usr/share/nipap/nipap-cli
  environment:
    PATH: "/usr/share/nipap/venv/bin:{{ ansible_env.PATH }}"

- name: Template nipap configuration file
  ansible.builtin.template:
    src: ../templates/nipap.conf.j2
    dest: /etc/nipap/nipap.conf
    mode: "0644"

- name: Initialize SQLite auth database
  ansible.builtin.shell: |
    source /usr/share/nipap/venv/bin/activate
    nipap-passwd create-database -u "{{ nipap_admin_user }}" -p "{{ nipap_admin_password }}" -n "admin user"
  args:
    executable: /bin/bash

- name: Create directory /var/run/nipap
  ansible.builtin.file:
    path: /var/run/nipap
    state: directory
    owner: "{{ nipap_user }}"
    group: "{{ nipap_group }}"
    mode: "0755"

- name: Auto install NIPAP database
  ansible.builtin.shell: |
    source /usr/share/nipap/venv/bin/activate
    /usr/sbin/nipapd --auto-install-db
  args:
    executable: /bin/bash

- name: Create NIPAP web UI user
  ansible.builtin.shell: |
    source /usr/share/nipap/venv/bin/activate
    nipap-passwd add -u "{{ nipap_webui_user }}" -p "{{ nipap_webui_password }}" -n "NIPAP web UI" -t
  args:
    executable: /bin/bash

- name: Ensure /etc/nipap/www directory exists
  ansible.builtin.file:
    path: /etc/nipap/www
    state: directory
    mode: "0755"

- name: Copy nipap-www.wsgi file
  ansible.builtin.copy:
    src: ../files/nipap/nipap-www.wsgi
    dest: /etc/nipap/www/nipap-www.wsgi
    mode: "0644"

- name: Copy nipapd systemd service file
  ansible.builtin.copy:
    src: ../files/nipap/nipapd.service
    dest: /etc/systemd/system/nipapd.service
    mode: "0644"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Ensure nipapd service is running and enabled
  ansible.builtin.systemd:
    name: nipapd
    state: started
    enabled: true

- name: Configure httpd for NIPAP web UI
  ansible.builtin.copy:
    src: ../files/httpd/nipap.conf
    dest: /etc/httpd/conf.d/nipap.conf
    mode: "0644"

- name: Configure httpd for NIPAP web UI
  ansible.builtin.copy:
    src: ../files/httpd/httpd.conf
    dest: /etc/httpd/conf/httpd.conf
    mode: "0644"

- name: Ensure httpd service is running and enabled
  ansible.builtin.systemd:
    name: httpd
    state: started
    enabled: true
