nipap_user: nipap
nipap_group: nipap
nipap_home: /opt/nipap
nipap_database_user: nipap
nipap_database: nipap
nipap_database_user_password: nipap123
nipap_listen: 0.0.0.0
nipap_port: 1337
nipap_foreground: false
nipap_debug: false
nipap_forks: 0
nipap_db_host: 127.0.0.1
nipap_db_port: 5432
nipap_xmlrpc_uri: http://{{ nipap_webui_user }}:{{ nipap_webui_password }}@127.0.0.1:{{ nipap_port }}
nipap_secret_key: "SoE45aS64AJDf1Xtwaz6"
nipap_url: http://192.168.101.20:8181
nipap_admin_user: admin
nipap_admin_password: "H1b8k06CyBWPcnMx0a1F"

nipap_webui_user: webadmin
nipap_webui_password: "NHTvu1aNFb61Lzy75HxN"

# PostgreSQL variables
postgresql_login_unix_socket: /var/run/postgresql
postgresql_restarted_state: "restarted"
postgresql_python_library: "python3-psycopg2"
postgresql_unix_socket_directories:
  - "{{ postgresql_login_unix_socket }}"
postgresql_service_state: started
postgresql_service_enabled: true
postgresql_users:
  - name: "{{ nipap_database_user }}"
    role_attr_flags: SUPERUSER
    password: "{{ nipap_database_user_password }}"
postgresql_databases:
  - name: "{{ nipap_database }}"
    owner: "{{ nipap_database_user }}"
postgres_users_no_log: false
postgresql_enablerepo: "pgdg17"
postgresql_version: "17"
postgresql_data_dir: /var/lib/pgsql/17/data
postgresql_bin_path: /usr/pgsql-17/bin
postgresql_config_path: /var/lib/pgsql/17/data
postgresql_daemon: postgresql-17.service
postgresql_packages:
  - postgresql17
  - postgresql17-server
  - postgresql17-libs
  - postgresql17-contrib
  - postgresql17-devel

# Nipap data generation variables
vrfs_file: "{{ output_dir }}/nipap/vrfs.json"
vlans_file: "{{ output_dir }}/nipap/vlans.json"
prefixes_file: "{{ output_dir }}/nipap/prefixes.json"
# ip_addresses_file: "{{ output_dir }}/nipap/ip_addresses.json"

# admin_nipap_api_token: 2247a0371d4e186a5c78f3e13417970d5672b3b1
