- name: Create the vrfs using Python
  ansible.builtin.script:
    cmd: ../scripts/create_vrfs.py "{{ vrfs_file }}"
    executable: "{{ python_path }}"
  delegate_to: localhost
  become: false
  when: lookup('ansible.builtin.fileglob', vrfs_file) == []

- name: Create the vlans using Python
  ansible.builtin.script:
    cmd: ../scripts/create_vlans.py "{{ vlans_file }}"
    executable: "{{ python_path }}"
  delegate_to: localhost
  become: false
  when: lookup('ansible.builtin.fileglob', vlans_file) == []

- name: Create the subnets using Python
  ansible.builtin.script:
    cmd: ../scripts/create_subnets.py "{{ vrfs_file }}" "{{ prefixes_file }}"
    executable: "{{ python_path }}"
  delegate_to: localhost
  become: false
  when: lookup('ansible.builtin.fileglob', prefixes_file) == []

- name: Create the IP addresses using Python
  ansible.builtin.script:
    cmd: ../scripts/create_ip_addresses.py "{{ vrfs_file }}" "{{ prefixes_file }}" "{{ ip_addresses_file }}"
    executable: "{{ python_path }}"
  delegate_to: localhost
  become: false
  when: lookup('ansible.builtin.fileglob', ip_addresses_file) == []
